M48
; DRILL file {KiCad 6.0.4} date Sun 24 Apr 2022 08:12:00 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-24T20:12:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
%
G90
G05
T1
X6.9724Y-3.8362
X6.9724Y-4.0638
T2
X5.3601Y-3.0646
T0
M30
